# Stage 1: Build the NestJS application
FROM node:20.10.0 AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

# Generate Prisma Client
RUN npx prisma generate


CMD ["npm", "run", "start",":dev"]